spring:
  datasource:
    url: jdbc:oracle:thin:@st-db-aws.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_st_4
    password: cotosst4issharedprocess
    driverClassName: oracle.jdbc.OracleDriver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-active: 5
      min-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_st_4
