spring:
  datasource:
    url: jdbc:oracle:thin:@dev-db.cotos.ricoh.co.jp:1521/pdb1
    username: ci_batch_release_0308_backlog
    password: ci_batch_release_0308_backlog
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: ci_batch_release_0308_backlog