spring:
  datasource:
    url: jdbc:oracle:thin:@dev-db.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_local_release_0824
    password: cotos_local_release_0824
    driverClassName: oracle.jdbc.OracleDriver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-active: 5
      min-idle: 1
  main:
    web-environment: false
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_local_release_0824
  jackson:
    time-zone: Asia/Tokyo
  messages:
    basename: Messages
    defaultEncoding: UTF-8
cotos:
  # ユーザー設定
  mom:
    system:
      momEmpId: COTOS_BATCH_USER
      operatorName: dummy_batch_operator
      operatorOrgName: dummy_batch_operator_org
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
