spring:
  datasource:
    url: jdbc:oracle:thin:@dev-db.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_dev
    password: cotos_dev
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_dev