spring:
  datasource:
    url: jdbc:oracle:thin:@dev-db.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_dev_1
    password: cotos_dev_1
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_dev_1
cotos:
  authentication: https://dev-api-1.cotos.ricoh.co.jp/auth/api/auth
  # 手配APIURL
  arrangement:
    url: https://dev-api-1.cotos.ricoh.co.jp/arrangement/api
  # 契約APIURL
  contract:
    url: https://dev-api-1.cotos.ricoh.co.jp/contract/api