spring:
  datasource:
    url: jdbc:oracle:thin:@st-db-aws.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_st_1
    password: cotosst1issharedprocess
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_st_1
cotos:
  authentication: https://st-api-1-aws.cotos.ricoh.co.jp/auth/api/auth
  disp:
    urls:
      domain: https://st-1-aws.cotos.ricoh.co.jp/
      screenName: ContractScreen