spring:
  datasource:
    url: jdbc:oracle:thin:@dev-db-aws.cotos.ricoh.co.jp:1521/pdb1
    username: cotos_dev_2
    password: cotos_dev_2
    driverClassName: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: cotos_dev_2
cotos:
  authentication: https://dev-api-2-aws.cotos.ricoh.co.jp/auth/api/auth
  disp:
    urls:
      domain: https://dev-2-aws.cotos.ricoh.co.jp/
      screenName: ContractScreen