spring:
  datasource:
    url: jdbc:oracle:thin:@dev-db.cotos.ricoh.co.jp:1521/pdb1
    username: anada
    password: anada
    driverClassName: oracle.jdbc.OracleDriver
  main:
     web-environment: false
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: anada
  jackson:
    time-zone: Asia/Tokyo
  mail:
    default-encoding: UTF-8
    host: shipyard.cotos.ricoh.co.jp
    port: 1025
    username: koike.shinichi
    password: koike.shinichi
  messages:
    basename: Messages
    defaultEncoding: UTF-8

cotos:
  mom:
    system:
      momEmpId: COTOS_BATCH_USER
      operatorName: dummy_batch_operator
      operatorOrgName: dummy_batch_operator_org
  authentication: https://dev-api.cotos.ricoh.co.jp/auth/api/auth
  auth:
    throughURIs: /swagger-ui.html, /swagger-resources/**, /swagger/**, /webjars/**, /v2/api-docs**, /api/living
    jwt:
      secretKey: cotosSecretKey
      claims:
        momEmpId: momEmpId
        singleUserId: singleUserId
        origin: origin
        applicationId: applicationId
    headers:
      authorization: X-Cotos-Authorization
      requireDispAuthorize: X-Cotos-Require-Disp-Authorize
      requireMomAuthorize: X-Cotos-Require-Mom-Authorize
      dispAuthorization: X-Cotos-Disp-Authorization
      momAuthorization: X-Cotos-Mom-Authorization
      contentType: Content-type
      filename: filename
  mail:
    fromMailAddress: test@example.com
  api:
    standard:
      contract: https://dev-api-1.cotos.ricoh.co.jp/contract/api
    electric:
      estimation: https://dev-api-1.cotos.ricoh.co.jp/estimation/electric/api
      contract: https://dev-api-1.cotos.ricoh.co.jp/contract/electric/api
  external:
    database:
      schema: cotos_electric_ext_standard
remote:
 momauthority:
  url: http://165.96.254.183:10110/jmo/services/KengenService
  relatedid: CSP